all: HelloWorld.exe pointers.exe Polish.exe Linked_List.exe Guessing_Game.exe Polishv2.exe Strings_Exercises.exe Temperature.exe

HelloWorld.exe: HelloWorld.c
	gcc HelloWorld.c -o HelloWorld.exe

pointers.exe: 6Pointers.c
	gcc 6Pointers.c -o pointers.exe

Polish.exe: Polish.c
	gcc Polish.c -o Polish.exe

Polishv2.exe: Polishv2.c
	gcc Polishv2.c -o Polishv2.exe

Guessing_Game.exe: Guessing_Game.c
	gcc Guessing_Game.c -o Guessing_Game.exe

Strings_Exercises.exe: Strings_Exercises.c
	gcc Strings_Exercises.c -o Strings_Exercises.exe

Temperature.exe: Temperature.c
	gcc Temperature.c -o Temperature.exe

Linked_List.exe: Linked_List.c
	gcc Linked_List.c -o Linked_List.exe

clean:
	rm *.exe
